### ISSUE TITLE
Stage 2. Basics Tutorials Task and Python

### ISSUE THREAD

**Issue by ydmeta** [djfedos/djfedos-boostrap#1]
# Stage 2. Basics Tutorials Task and Python

## Read Documentation of Taskfile**

it's an amazing tool for semantic automation
Last 3 companies I worked in adopted it widely.
So it's not some "my" thing ;)

Try to play with example from usage.
> [taskfile](https://taskfile.dev/#/)

You will need to learn some bash, it also very useful.

### Python tutorials Links

- https://www.mygreatlearning.com/blog/python-tutorial-for-beginners-a-complete-guide/
- Big one
- https://docs.python-guide.org/intro/learning/
- https://www.youtube.com/watch?v=_uQrJ0TkZlc
- https://www.dataquest.io/blog/learn-python-the-right-way/
- https://docs.python.org/3/tutorial/
- https://www.youtube.com/watch?v=rfscVS0vtbw

### Python Subjects Basic List

make sure you cover most of next areas:

- variables
  - definitions
  - assignments
- types
  - primitives
    - int, float
    - str
    - bool
  - complex
    - list
    - dict
    - object
    - type (classes)
- assignment (by value, by reference)
- functions
  - definitions (signatures)
  - usage
  - parameter passing (by value, by reference)
     - defaults
     - args, kwargs
  - scope of variable
- import system
  - modules
  - packages
- work with files (IO part) (open, read, write, close)
- exceptions (through, catch)

- https://khuyentran1401.github.io/Efficient_Python_tricks_and_tools_for_data_scientists/how_to_read.html

**Comment by djfedos** [comment]
@ydmeta,
today I've learned how git works from this course: https://www.pluralsight.com/courses/how-git-works
just to have an idea

**Comment by djfedos** [comment]
a good explanation of scope is here: https://thepythonguru.com/python-functions/#global-variables-vs-local-variables
scope is the area where we can access the variable. if the variable is declared inside the function, we can access it only inside this function. we can declare a global variable either outside of any functions or in a function with the keyword global, but it's not recommended to do so

**Comment by djfedos** [comment]
video course https://www.youtube.com/watch?v=rfscVS0vtbw complete, see djfedos-boostrap/notebooks/python_video_course_nb.py for details
