### ISSUE TITLE
Stage 1.1 Add flipper.py that can flip provided image and write text on it

### ISSUE THREAD

**Issue by ydmeta** [djfedos/djfedos-boostrap#2]
running params PATH_TO_IMAGE TEXT_TO_WIRITE

```
python flipper.py path/to/image.jpg --TEXT_TO_WIRITE MY_TEXT
```

Use fire for CLI with python default params for function call.
use open cv for image transformations
before starting please read about variable and file access.
this programm should read PATH_TO_IMAGE image from jpg file
flipe it on horizontal axis
and write on the flipped image provided TEXT_TO_WIRITE

firest make it show result image
than add flag --save, so image will be saved in provided path

```
python flipper.py path/to/image.jpg --TEXT_TO_WIRITE MY_TEXT --save path/to/flipped_result.jpg
```

add test task (test-flipper-base) which runs next line

```
python flipper.py path/to/image.jpg --TEXT_TO_WIRITE MY_TEXT --save path/to/flipped_result.jpg
```

and check that file (path/to/flipped_result.jpg) is created and non zero size.

**Comment by djfedos** [comment]
@ydmeta, FYI
the task is complete
